#!/bin/bash

echo "💳 Checking AWS Payment Method Status"
echo "======================================"
echo ""

echo "📋 Opening AWS Billing Console..."
echo ""
echo "Please check the following:"
echo ""
echo "1. Payment Methods Page:"
echo "   https://console.aws.amazon.com/billing/home#/paymentmethods"
echo ""
echo "   ✅ Check if your card shows 'Verified' status"
echo "   ✅ Check if it's set as 'Default'"
echo ""
echo "2. Account Status Page:"
echo "   https://console.aws.amazon.com/billing/home#/account"
echo ""
echo "   ✅ Check 'Payment Method' section"
echo "   ✅ Look for any warnings or alerts"
echo ""
echo "3. If card is NOT verified:"
echo "   - Check your email for verification link"
echo "   - Check spam/junk folder"
echo "   - Wait 10 minutes and refresh"
echo "   - Try removing and re-adding the card"
echo ""
echo "4. Alternative: Try Bedrock Playground"
echo "   https://console.aws.amazon.com/bedrock/home?region=ap-south-1#/chat-playground"
echo ""
echo "   - Select 'Anthropic' → 'Claude 3 Haiku'"
echo "   - Try to send a message"
echo "   - This might trigger the subscription flow"
echo "   - Accept any terms that appear"
echo ""
echo "======================================"
echo ""
echo "After verifying/fixing payment method:"
echo "  python3 test_bedrock_direct.py"
echo ""
